# Docker Compose file for development

version: '2.1'
services:
  app:
    build: .
    command: 'yarn start:prod'
    depends_on:
      - mongo
      - redis
    volumes: # TODO: use in-container files instead in production (?)
      - .:/usr/src/movieFreak
      - /usr/src/movieFreak/node_modules
    ports:
      - "80:80"
    environment:
      NODE_ENV: production # TODO: change this to 'production' on production
      MOVIEFREAK_API_PORT: 80
      MOVIEFREAK_API_SECRET: "[ moviefreak_api_secret ]" # TODO: change this on production
      BASE_URL: "http://localhost"
      API_URL: "http://localhost/api"
      MONGODB_URL: "mongodb://mongo:27017/movie"
      REDIS_HOST: redis
      REDIS_PORT: 6379 # Using default redis image port
    restart: always # TODO: change this to 'always' on production
  mongo:
    image: "mongo"
    container_name: "mongo"
    environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
    command: mongod --smallfiles --logpath /dev/null
    restart: always  # TODO: change this to 'always' on production
  redis:
    image: "redis:alpine"
    restart: always # TODO: change this to 'always' on production
  mongo-seed:
    build: ./server/mongo-seed
    links:
      - mongo