# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20170806_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='imageURL',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='produk',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
